[package]
name = "quotes-api"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "3.3.2"
serde = "1.0.130"
serde_json = "1.0.68"
serde_derive = "1.0.130"
strum = "0.21.0"
strum_macros = "0.21.1"
yahoo_finance_api = "1.2.2"
